name: Build responses.db

on:
  push:
    paths:
      - 'data/**'
      - 'db/init.js'
      - 'package.json'

jobs:
  build-db:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run init-db script
        run: node db/init.js

      - name: Commit responses.db
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add db/responses.db
          git commit -m "Auto-generate responses.db"
          git push
        continue-on-error: true
