name: 🛠️ Build responses.db

# متى ينشتغل الـ Workflow؟
on:
  push:
    paths:
      - 'data/**/*.json'   # لما تعدل أي JSON
      - 'db/init.js'       # أو تعدل سكربت التهيئة
      - 'package.json'     # أو تضيف/تغير سكربت init-db

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. إحضار الكود من الريبو
    - uses: actions/checkout@v3

    # 2. تثبيت Node.js
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    # 3. تثبيت الاعتماديات
    - name: Install dependencies
      run: npm ci

    # 4. تشغيل سكربت init-db
    - name: Build responses.db
      run: npm run init-db

    # 5. إذا تغيّر responses.db: نعمل commit ونرجعه للريبو
    - name: Commit & Push responses.db
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add db/responses.db
        # لو ما في تغييرات، ننهي؛ وإلا نعمل commit + push
        git diff --quiet && echo "No changes in db." || (git commit -m "chore: update responses.db" && git push)
