name: Build responses.db

on:
  push:
    paths:
      - 'data/**'
      - 'db/init.js'
      - 'package.json'
  workflow_dispatch:

jobs:
  build-db:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run init-db script
        run: node db/init.js

      - name: Commit responses.db if exists
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          if [ -f db/responses.db ]; then
            git add db/responses.db
            git commit -m "chore: auto-generate responses.db"
            git push
          else
            echo "⚠️ responses.db not found, skipping commit."
          fi
